// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALMme_sxYpXxXUx4A1mZ_0Eb_lJ-KvL_4',
    appId: '1:629371622541:web:685b4ff9cadf93deb5bec4',
    messagingSenderId: '629371622541',
    projectId: 'pictionnary-etna',
    authDomain: 'pictionnary-etna.firebaseapp.com',
    storageBucket: 'pictionnary-etna.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFBlNbS0QWJ5V0Fi7_O19IjRlwMrFvTA4',
    appId: '1:629371622541:android:9a12dc3dcce299aab5bec4',
    messagingSenderId: '629371622541',
    projectId: 'pictionnary-etna',
    storageBucket: 'pictionnary-etna.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADkypANmFUK9P53XBtY74THG4kW5iRJPI',
    appId: '1:629371622541:ios:67adae333f146ebcb5bec4',
    messagingSenderId: '629371622541',
    projectId: 'pictionnary-etna',
    storageBucket: 'pictionnary-etna.appspot.com',
    iosBundleId: 'com.example.pictionnary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADkypANmFUK9P53XBtY74THG4kW5iRJPI',
    appId: '1:629371622541:ios:67adae333f146ebcb5bec4',
    messagingSenderId: '629371622541',
    projectId: 'pictionnary-etna',
    storageBucket: 'pictionnary-etna.appspot.com',
    iosBundleId: 'com.example.pictionnary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALMme_sxYpXxXUx4A1mZ_0Eb_lJ-KvL_4',
    appId: '1:629371622541:web:afe1a5c79bcfe9e3b5bec4',
    messagingSenderId: '629371622541',
    projectId: 'pictionnary-etna',
    authDomain: 'pictionnary-etna.firebaseapp.com',
    storageBucket: 'pictionnary-etna.appspot.com',
  );

}